### PR TITLE
Fix YAML errors

### PR DESCRIPTION
**Pull request by febuiles**
- In Ruby 1.8.7 and 1.9.2 YAML will fail with `ArgumentError` when it receives the Github post-receive POST. This should fix it.

### CODE REVIEW

**Comment by queso** [comment]
I can confirm I am seeing this error on 1.8.7 with the 0.8.1 gem.  Did something change on the github payload side?  The JSON.parse call seems to work fine without needing a rescue...

**Comment by defunkt** [comment]
I don't think the YAML is the problem here.

**Comment by febuiles** [comment]
Chris: Do you have any other stuff to check into then? The Github payload (JSON) is not valid to be parsed by YAML and it will error out. I gotta admit I don't quite know why it's expecting YAML.

**Comment by queso** [comment]
Why was this closed?  I am still having this issue with the latest version and the payload from Github.

**Pull request closed without merging**
