### PR TITLE
Fixing Munge of ENV

### PR DESCRIPTION
**Pull request by jkamenik**
I had a problem where all the builds started to fail except the first after a CIJoe restart.  I traced the problem to the munging of the ENV when a hook is called.  I have slightly modified the run_hook function to provide a clean ENV to the hook file, but to reinstate the ENV for the next build.

### CODE REVIEW

**Comment by nt** [comment]
Hello @jkamenik,

I am currently runnin into some trouble with my CI Joe setup. It looks like the same bug you encountered. Could you confirm please ? 

http://stackoverflow.com/questions/6030840/rails-dependency-problem-within-ci-joe

Thank you,

Nicolas.

**Comment by jkamenik** [comment]
Your setup seems to be similar to mine.  I was using RVM, but because the ENV pollution it would not stay clean CIJoe would only checkout and build 1 time then it would crash.  My ci command was `rvm use 1.8.7@gemset; bundle install; rake spec`.  After the first build the gem set would be wrong and cijoe could not handle it.  Cleaning the ENV prevents ENV changes from effecting CIJoe.

**Comment by queso** [comment]
hey guys,

Thanks for sending in the pull request, I will try to get this tested and merged in the next day or so.

**Comment by nt** [comment]
Thanks @jkamenik. I tried your patch, it worked like a breeze. I'm up and running :)
Cheers from France.

**Comment by coverall** [comment]
Ah, this is just what I need! Hope this gets merged in :)

**Comment by jacqui** [comment]
Yes please!

**Comment by dblock** [comment]
+1 fixes it for me

**Pull request merged**
