### PR TITLE
Rescue from YAML and fix build status.

### PR DESCRIPTION
**Pull request by febuiles**
Rescue from YAML: In Ruby 1.9.2 YAML will fail with `ArgumentError: syntax error on line 0, col 132` when it receives the Github post-receive POST. This should fix it.

I also noticed that the build fields are updated in `CIJoe#build!` in an instance variable but they're never assigned back to `@current_build`. Stuff like the Campfire notifier needs this information to post the log in the chat so I just copied it back.

### CODE REVIEW

**Comment by febuiles** [comment]
Added a second fix for Ruby 1.9.

**Comment by queso** [comment]
febuiles,

Do you know why this was closed or how did you fix it?  I am getting the same issue under ruby 1.8.7 REE.

**Comment by febuiles** [comment]
I closed it and created another one to split it in 2 requests. The YAML one should be up later :)

**Comment by queso** [comment]
febuiles,

Be sure to test hitting the build button by hand, I am seeing errors with an empty post and your solution.

**Comment by febuiles** [comment]
queso: If you change your server.rb to https://gist.github.com/815685 it should work. I'm trying to find a cleaner solution that works in 1.8 and 1.9.

**Comment by Mint-6263** [comment]
@febuiles

**Pull request closed without merging**
