### PR TITLE
Config splats were fucked on 1.9

### PR DESCRIPTION
**Pull request by jbarnette**
...and now they're not. Tested in production.

### CODE REVIEW

**Comment by kitplummer** [comment]
Can confirm fix on 1.9.2-p0 on Ubuntu 10.04 and MacOS 10.6.   Cheers.

**Comment by zenom** [comment]
I can confirm on CentOS as well.

**Comment by cimm** [comment]
I can confirm this works on 1.9.2-p0 on Ubuntu as well. Thanks!

**Comment by dennisreimann** [comment]
+1

**Comment by rtomayko** [comment]
Merged. Thanks!

**Pull request merged**
