### PR TITLE
Build queue supports branches

### PR DESCRIPTION
**Pull request by mcolyer**
Currently if the build queue is enabled and you queue a branch to build and another branch is currently being built, CI Joe forgets which branch you asked to build. This pull request implements a simple in memory queue to capture that information branch.

Branches are built in the order requested and if a request has already been made for a branch a second one won't be added. This branch also changes the configuration option slightly, as a file location is no longer required (an updated README is included).

### CODE REVIEW

**Comment by queso** [comment]
mcolyer,

This looks interesting.  Just curious, why add the logging method, just for debugging?

**Comment by mcolyer** [comment]
I added the debugging as it seemed appropriate with the other types of logging already currently in cijoe. It's also currently the only way to tell if your branch has been added to the queue or not.

**Comment by cmeiklejohn** [comment]
I'd love to see this added.  Anything I can do to help?

**Comment by cmeiklejohn** [comment]
Any movement here?  Would love to see this pulled in.

**Comment by cmeiklejohn** [comment]
Bump.

**Comment by cmeiklejohn** [comment]
Bump.  Is anyone actively maintaining this at this point?

**Pull request merged**
