### PR TITLE
Fix the post method to properly decode the json

### PR DESCRIPTION
**Pull request by queso**
This patch includes both tests and fixes for the issue with json decoding and for clicking the build button.  The logic wrapper line 39 (joe.build) had payload.empty?, which was true every time because the payload isn't being handled right.

I added failing tests to ensure that doesn't happen again, as well as tests with actual payloads from Github.  I also had to stub out joe.build! as it kept force resetting the local git repo with the remote master.

### CODE REVIEW

**Comment by queso** [comment]
Chris,

Is this something you will be pulling in?  I can't figure out how to send multiple pull requests and I have more work in my queue for cijoe...  I've created a companion gem for multi-project dashboard called general-hawk!

**Comment by queso** [comment]
Hmm,

I guess the pull request has all my commits on my repo?  Either way, I refactored campfire to be it's own class for ease of testing.  I also added more info to the json erb file so I can parse it for my new multiproject home page called "General Hawk"

**Comment by queso** [comment]
Chris,

Any chance you could look into merging this stuff, I have a blog post ready to go that explains a much simpler multi-project setup.

You can see "general-hawk" gem in action with cijoe here: http://ci.fourbeansoup.com/

**Comment by queso** [comment]
This has been merged

**Comment by donaldpiret** [comment]
Would love to see that blogpost, general-hawk looks very interesting as we're currently looking for a simple way to use cijoe in a multi-project setup

**Pull request closed without merging**
